### ISSUE TITLE
legendary as Lutris Runners

### ISSUE THREAD

**Issue by mrintrepide** [derrod/legendary#11]
For GUI, why not create a EGS Runners with legendary ?

[https://github.com/lutris/lutris/tree/master/lutris/runners](https://github.com/lutris/lutris/tree/master/lutris/runners)

**Comment by derrod** [comment]
Well Legendary is cross-platform and the GUI is supposed to work on Windows and Linux, a Lutris runner also wouldn't solve installation/downloading stuff. But a runner or similar it is a possibility for handling online authentication and dealing with DRM.

**Comment by mrintrepide** [comment]
If legendary(-cli) is installed as shell command like steam, isn't it possible to write in a Lutris game script installer a 'execute' command with "legendary download <game name>" ?
For login (no lutris gui for this) or online (set dynamic game flags at launch ?) it's more complicated.

**Comment by derrod** [comment]
Lutris has a WIP PR for some EGS integration, I'd say that waiting for that to be merged and then piggybacking off of it might be easier than starting from scratch: https://github.com/lutris/lutris/pull/2523

Theoretically Lutris could import legendary as a package and use most of its features including launching, DRM support, and some game management without having to go through the CLI. The only thing that wouldn't work (afaik) is the downloader because it requires python 3.8+ but Lutris targets a loewr version.

**Comment by dotevo** [comment]
Maybe it is offtopic. I would prefer to integrate Legendary to with GameHub: https://tkashkin.tk/projects/gamehub/

**Comment by derrod** [comment]
That should probably be a seaprate issue, possibly not even on this repo. Looking at gamehub I think it could work from their side by reading legendary's config files to get the metadata - that seems to be what they do for Steam - and then just invoking it for launching games.
 I'm not familiar with the language their app is written in so that's probably not something I'd take up myself.

**Comment by buxel** [comment]
@derrod I'm the author of the EGS PR at lutris. 

Integrating EGS itself is not an ideal solution, because it provides close to no API/CLI to work with. Legendary was not around when i started implementing this (for personal use) and now i shared it because i lack time to push this forward. @Steinhagen has picked up some of the work, tough.

There are ways to work around most of the issues, but to be honest, i think from a maintenance perspective it will be much easier to integrate Legendary instead of EGS into lutris.

I had a quick look at the options you already provide and the only challenge might be letting lutris manage the wine prefix and some of the game's configuration specific to Legendary. 

We could have game settings similar to your config file and __somehow__ pass them to Legendary when launching the game.
 ```
; Settings to only use for "AppName"
[AppName]
; launch game without online authentication by default
offline = true
; Skip checking for updates when launching this game
skip_update_check = true
; start parameters to use (in addition to the required ones)
start_params = -windowed
wine_executable = proton

[AppName.env]
; environment variables to set for this game (mostly useful on linux)
WINEPREFIX = /mnt/tank/games/Game/.wine
DXVK_CONFIG_FILE = /mnt/tank/games/Game/dxvk.conf
 ```

Authentication can be handled in the global runner settings.

**Comment by derrod** [comment]
Loading game specific overrides form the game folder is certainly a possibility if you don't want to meddle with the config directly. It could be either another .ini file (e.g `.legendary.ini`) or a JSON file (.e.g `.legendary.json`) that lives in the installation directory. Whichever is easier.

**Comment by buxel** [comment]
Yes, i'd like to avoid patching up a single shared config file for different games. 

But on the other hand your suggestion imposes the question if which config takes priority and might lead to confusion if there is some stuff for a specific game configured globally, and other parts in a separate file.

My suggestion for priority of configuration:
1) cli arguments
2) game-specific config
3) global config

Higher priority simply overwrites lower ones. The reason for cli being at the top is that (in my opinion), those are set manually and very intentionally. Similar to how this is handled in [.NET core](https://devblogs.microsoft.com/premier-developer/order-of-precedence-when-configuring-asp-net-core/)

**Comment by derrod** [comment]
All environment variables you pass to Legendary will be passed on to WINE/the game as well. So it is certainly possible to add some for legendary itself as well.

**Comment by buxel** [comment]
I think this should be the way to go then. Time for some tinkering... :wink:

**Comment by buxel** [comment]
should i also take a look at supporting environment variables in Legendary as well, or is that something, you can put on your roadmap? 
I'd like to implement this in lutris up to the point where we can hand over all arguments and ENV to Legendary and see where we can go from there.

The WIP can be found here: https://github.com/buxel/lutris/tree/legendary-runner

**Comment by derrod** [comment]
I have some WIP changes to how some config stuff works in my local tree that would make a PR merge-conflict hell so please tell me what ENV variables you'd like to have an I can see about implementing them. I plan to push out another release with cloud save support and those changes sometime this week.

**Comment by derrod** [comment]
There could also be some changes to how authentication works, since all you really need is that exchange code and Lutris can already handle embedded websites with redirects (see GoG auth) you could do the entire login within it. And then pass the exchange code to legendary via a new command line flag (e.g. `legendary auth --code <code>`) to avoid having to spawn a terminal at all.

**Comment by buxel** [comment]
To let lutris manage wine+prefix, the settings for `wine_executable` and `WINEPREFIX` should be enough.

If we add auth like in GOG (Syncer), it will be a little odd for people only using the runner and no sync feature. There is no "GOG runner" because after downloading the games, the wine runner takes over.
DRM is coupled to auth, but in lutris there is no concept of auth for runners. Steam uses auth, but lutris simply expects the client to be logged in already. But maybe I'm missing something...

Either way, implementing auth properly in a Syncer will be a necessary step after we teach a runner to talk to Legendary.

**Comment by derrod** [comment]
Ah yeah fair enough, I'm not too familiar with Lutris. I've just had a high level look at it and some internals a while ago when I was seeing if it was viable to implement a downloader for Twtich Prime games (seemed easier than finishing [twl.py](https://github.com/derrod/twl.py)) like they have for GOG.

**Comment by buxel** [comment]
I managed to install and launch a game (on my machine). It seems like the `WINEPREFIX` environment set up by Lutris is already picked up by Legendary 🥳 

Now, all i need for this POC is a way to tell Legendary which wine executable to use. It doesn't really matter if its via ENV or argument, whatever suits you better

**Comment by derrod** [comment]
I added some more ways of overriding the wine executable yesterday: https://github.com/derrod/legendary/commit/2945c6c91f828114254d5393ba49001ce07ada16

**Comment by buxel** [comment]
Made a PR: https://github.com/lutris/lutris/pull/2894

**Comment by derrod** [comment]
As there's not been any further development there I'll close this for now. I personally don't have time or interest to integreate legendary into Lutris, primarily because I don't think it really fits into the workflow and design of it. Maybe that is something to revisit in the future.

The Lutris folks are of course welcome to adopt things that may be useful for them, this is GPL licensed afte rall.
