### ISSUE TITLE
Question: so... how legit is this?

### ISSUE THREAD

**Issue by nhalase** [derrod/legendary#113]
So far from my testing, this tool is amazing! However, how exactly does it work? Is it using the Epic Online Services SDK, or is it using the undocumented REST API that Epic doesn't talk about?

I'm worried about getting invested in this just for Epic to find out about it and shut it down. :/

**Comment by CommandMC** [comment]
As far as I understood it, they won't be able to shut this down without also crippling some of their services (legendary sends the same User Agent String as the Epic Games Launcher, so I don't think they can detect it that easily)

**Comment by Jawschamp** [comment]
Hey there, Epic has no intentions on shitting this down this is not the first tool to do what Legendary is doing its very unlikely that Epic will do anything about unless it has to do with account security but where it is right now it's not likely to be an issue.

**Comment by asdf2345** [comment]
> Hey there, Epic has no intentions on shutting this tool down. This is not the first tool to do what Legendary is doing, it's very unlikely that Epic will do anything about this unless it has to do with account security, but where it is right now it's not likely to be an issue. Hope that clears your concerns up, the most likely thing that could make this stop working other then shutting it down would be for the Dev to stop supporting it. But there are alternatives.

What alternatives?

**Comment by derrod** [comment]
Legendary uses the private APIs that the Epic Games Launcher uses. If they break those it'll break, but as long as somebody's there to fix it that's not realy a big problem. I doubt they really care about Legendary's existence anyway since it doesn't do anything harmful to their platform or business. Whether or not you want to use it is up to you, you can have the EGL sync enabled and always fall back to using their official launcher in case it stops working.
