### ISSUE TITLE
Borderlands 2 online support

### ISSUE THREAD

**Issue by andremeireles** [derrod/legendary#127]
The game was installed on a windows partition. I put this line in **$HOME/.config/legendary/config.ini**

`install_dir = /run/media/Windows/Epic Games/Borderlands2`

and the command-line:

`legendary import-game Dodo "/run/media/Windows/Epic Games/Borderlands2"`

The game won't launch. The terminal stay stuck at: `0024:fixme:ntdll:EtwEventUnregister (deadbeef) stub.`

If i change the executable parameter from `Launcher.exe` to `Borderlands2.exe`, the game launch but stay stuck at checking download content.
I do have Handsome Collection and Lilith DLCs.

I need to do extra steps?

**Comment by derrod** [comment]
The game should work fine, at least when I tested it with Proton it did (though you do have to bypass the launcher). Make sure you're launching it from Legendary so it has the online authentication data (either rename the .exe or change `installed.json` to launch the real game instead of the launcher).
