### ISSUE TITLE
Unable to resolve path

### ISSUE THREAD

**Issue by happysmack** [derrod/legendary#135]
I am running Legendary version "0.20.1" compiled from Github on Ubuntu 20.04.  I installed Rogue Company and soon realized that it uses Easy Anti Cheat.  So i just uninstalled the game.  Now I get the following error:

`[Core] ERROR: Unable to resolve path for mapped drive "\h" for WINE prefix at "/home/desk/Games/epic-games-store"` 

![Screenshot from 2020-11-13 09-08-10](https://user-images.githubusercontent.com/10453370/99084169-9d565380-2594-11eb-90bb-92a1fac1bc90.png)

When I run `legendary -y egl-sync` I get this:

![Screenshot from 2020-11-13 10-05-14](https://user-images.githubusercontent.com/10453370/99086685-dba14200-2597-11eb-9ae3-92281ce29305.png)

I get no errors in EGS.  But also can't get most games to load with EGS. Legendary Rocks !
If there is a more appropriate place to post this, I will delete the post.

**Comment by derrod** [comment]
I have an idea what this could be, and that would be a rather simple fix as well.

Check the `.manifest` files in `/home/desk/Games/epic-games-store/drive_c/ProgramData/Epic/EpicGamesLauncher/Data/Manifests` and find which one belongs to Rogue Company and check what it says in the `InstallLocation` key (or ideally just post the whole thing).

Since you've already uninstalled the game you can then simply remove that .manifest file from that folder, sometimes the Epic Games Store doesn't remove them for some reason.

**Comment by happysmack** [comment]
Worked Like a charm. Thank you.
