### ISSUE TITLE
MangoHud

### ISSUE THREAD

**Issue by larrryfisherthefisherman** [derrod/legendary#146]
How would I go about launching a game with Mangohud?

**Comment by CommandMC** [comment]
Never used Mangohud, but from their Readme it seems like you can either set `mangohud` as the wrapper for a game (adding it before e. g. Proton) or set the environment variable `MANGOHUD` to 1

**Comment by larrryfisherthefisherman** [comment]
I actually tried that already. Doesn't seem to work. Thanks for the fast response.

**Comment by larrryfisherthefisherman** [comment]
Oh I don't know how to set an environment variable in legendary

**Comment by derrod** [comment]
See the README or just set the envinronment variable when/before invoking legendary.

**Comment by aboode95** [comment]
@derrod can you help here please? I read the README but I am stuck.

### using Wrapper (failed, doesn't run the game)

I tried running the OpenGL command for the MangoHud and it seems to work. But since the game I am playing is using Vulkan, I have to run a different command but the wrapper isn't recognising it:
```
$ legendary launch Fowl --wrapper MANGOHUD=1
```
but this outputs the error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'MANGOHUD=1'
```
---

The code that worked for OpenGL:
```
legendary launch Fowl --wrapper mangohud
```

### Setting environment variable (failed, runs the game but won't display the ingame-overlay):

And about setting environment variable, I am unsure if I am doing it right but what I tried:
```
MANGOHUD=1 legendary launch Fowl
```

Can you please help me here?

**Comment by aboode95** [comment]
This is the reply I got from MangoHud creator when I asked about if there is something wrong with I am doing:

> "If legendary is already running, then using environment variables with these commands won't have any effect at all"

So, if such is the case that legendary already running in my pc, is there a way to stop it and then run it again with MangoHud?

**Comment by aboode95** [comment]
I just switched to Heroic which seems to be using Legendary in the back but it works with Mangohud with a simple checkbox. So that is nice! ^^
