### ISSUE TITLE
Rename download to install for consistency

### ISSUE THREAD

**Issue by fuzxi** [derrod/legendary#18]
The commands related to installation are `download`, `uninstall`, and `list-installed`. I think it would be more consistent if `download` were renamed to `install`. I can make a pull request for this if you agree.

**Comment by derrod** [comment]
I didn't like the "install" naming since you also can use it just to download the game but I do agree that it's confusing. I'm planning on using a [little hack](https://gist.github.com/sampsyo/471779) to allow aliasing of the command name so it won't break existing user's workflow. So please don't open a PR for that.
