### ISSUE TITLE
Alt Tabbing makes some games unresponsive (input no longer registers)

### ISSUE THREAD

**Issue by StefanLobbenmeier** [derrod/legendary#188]
Music and video are continuing to play, but input no longer registers to the application.

Workaround for me was to instead launch the game using Lutris, then Alt Tabbing becomes supported

Games to reproduce (so far):
- Hue
- Celeste

Not reproduced:
- Sherlock Holmes Crimes and Punishments (Alt Tab does not work at all)

**Comment by derrod** [comment]
Fuck if I know. Probably some dumb WINE thing. Try using Lutris' WINE with legendary instead of whatever you're running now. If that doesn't fix it then I have no idea. It's not a legendary issue either way, once the game is launched my responsibility ends (problems wihth incorrectly invoking WINE aside, which this isn't).

**Comment by CommandMC** [comment]
Enabling the Virtual Desktop setting of Wine often times helps with these input losses
And yes that is 100% a wine issue and thus doesn't belong here

@derrod To save you the time (and sanity lol) I've created a repo for tracking (and solving) Epic Games issues on *nix. Feel free to send people there that open issues here: [CommandMC/EpicLinux](https://github.com/CommandMC/EpicLinux)
