### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by estrange** [derrod/legendary#189]
hello,

a nice feature would be, when it would be possible to use legendary with multiple epic accounts.
(as example epic account 1 USER1 and epicaccount USER2)
maybe with other instance or in another way.

**Comment by derrod** [comment]
Not something I'm going to really do. On linux you could technically run the app with different environment variables set for the home dir so you have two separate config directories, but that's kinda jank. If you just want to switch between accounts quickly you can swap out the `user.json` in the config directory.

**Comment by estrange** [comment]
ah ok, thanks for fast answer....  
idea then, when using under windows... for starting a "game" using a .bat-file, that renames user.json (and back)... should work i think, and thats a good clue. 

 for longer activities... renaming manually (updating games.... installing... and so on).... 

thank you :)

**Comment by nathan-fiscaletti** [comment]
@derrod would you be open to a pull request that would add this feature? I might be interested in just adding the feature myself since I switch between accounts pretty frequently. The alternative is writing a script to swap out the `user.json` files before launching a game, but that's not the most favorable approach in my opinion.
