### ISSUE TITLE
Memory leaking?

### ISSUE THREAD

**Issue by SergeyLatyshev** [derrod/legendary#22]
I'm using the AUR version for Manjaro (v0.0.9) and trying to download Metro: Exodus. It starts downloading fine, but consumes more and more RAM until its amount (preset with max_memory option) runs out, and stops downloading after that. When I interrupt and restart legendary, it resumes downloading, but eventually the same happens.
[legendary-log.zip](https://github.com/derrod/legendary/files/4579784/legendary-log.zip)
![Screenshot_2020-05-05_16:45:03:294](https://user-images.githubusercontent.com/28780380/81049827-8651ed00-8ef1-11ea-953f-eee2d7157c0a.png)

**Comment by derrod** [comment]
Can you get a log with debug info?

Run `legendary -v install Snapdragon --dlm-debug` at least until the point where it stops writing. It seems the file writer worker does not die (which is what I'd usually expect), but that it is missing a chunk that never finishes downloading or something like that.

**Comment by SergeyLatyshev** [comment]
I ran that command, waiting.

**Comment by SergeyLatyshev** [comment]
[legendary-log.zip](https://github.com/derrod/legendary/files/4580608/legendary-log.zip)

**Comment by derrod** [comment]
I tested this on my Ubuntu and Windows machine with `--max-shared-memory 2048` (otherwise defaults) and it worked fine, so unfortunately I really don't have an idea what could be going wrong in your case. I see your internet connection isn't the fastest but I don't think that should affect things unless there's some weird race condition happening where the download results thread locks up.

One last thing to try may be to reduce the number of workers e.g. `--max-workers 1` and see what happens.

**Comment by SergeyLatyshev** [comment]
> I see your internet connection isn't the fastest but I don't think that should affect things unless there's some weird race condition happening where the download results thread locks up.

60 Mbps, fast enough for me.
I'm downloading Borderlands 3 now, and the program is using 5 GB of RAM after running for 45 minutes. If your Internet connection is much faster, maybe a game gets downloaded before too much RAM would be in use?

**Comment by derrod** [comment]
No, RAM usage goes up when data is cached for later (e.g. because the game re-uses the same chunks for a different file) or downloaded data cannot be flushed.

What I think might happen on a slower connection is that a download for one piece of data never finishes for some reason, so downloads keep going but it's endlessly waiting for that missing part before it can continue flushing data to disk.

Now that *shouldn't* happen since there is a 10 second timeout on downloads, so if it gets stuck it should eventually abort and retry. But maybe there is another situation where things can lock in a way that I haven't considered.

**Comment by derrod** [comment]
Okay I think I found the issue, when I changed the download timeout code I forgot to check for it being `None`, so there are connections lingering around that should have been killed, but aren't. I will release another fix later today that hopefully fixes that for you.

**Comment by SergeyLatyshev** [comment]
Thanks!
