### ISSUE TITLE
Crashes on Wine64 with "INTERNAL ERROR: cannot create temporary directory!"

### ISSUE THREAD

**Issue by deftdawg** [derrod/legendary#28]
I'm attempting to get **GTA V** running on OSX with Wine64.   GTA V is a Windows only binary, so while it is possible to auth and download it with legendary on OSX natively, ultimately the game will need to be installed and run on Wine64 if it is to work on Mac at all... 

Attempting to run legendary.exe within a cmd.exe crashes on Wine64 for OSX with the following:
```[##] INTERNAL ERROR: cannot create temporary directory!```
where ## is the number of the temporary folder it is creating.

It seems that PyInstaller is creating about 6 directories prefixed with ## in `%TMP%` in _MEI592, _MEI593, etc... 

These directories are not owned by the user and are not readable (`dir /q`) or accessible
```cmd
cd %TMP%\_MEI592
Access denied.
```
on the Host os they appear as:
```
d---------   2 user  wheel    64B 15 May 02:19 _MEI592
```

I'm not sure if this is an issue with PyInstaller on Wine specifically or a problem with how legendary is packed with PyInstaller.

I've not yet attempted to install Python and install legendary that way.

**Comment by derrod** [comment]
Legendary does not support macOS, and it certainly doesn't support running the Windows exe in WINE. And the latter is certainly not required since legendary will run the game via WINE by itself to begin with. But I don't know if that would even work because I have no idea what the state of WINE and DX emulation is on macOS.
