### ISSUE TITLE
Problem lauching Jotun Valhalla Edition on 64bit linux

### ISSUE THREAD

**Issue by daedhel** [derrod/legendary#32]
Hi, i'm trying to lauch Jotun Valhalla Edition this way:

$ legendary launch Grouse

and get this result:

0024:err:module:__wine_process_init L"Z:\\home\\j\\legendary\\Jotun\\Jotun.exe" 64-bit application not supported in 32-bit prefix

I am using an updated Voidlinux 64bit linux. Here is my " $ uname -a"

Linux tour 5.4.39_1 #1 SMP PREEMPT Wed May 6 19:42:50 UTC 2020 x86_64 GNU/Linux

Tell me if you need more info on my system.

**Comment by derrod** [comment]
This issue tracker should not be used for game/WINE issues since I can't really assist with that and it's not a problem with legendary itself. I recommend checking Linux gaming forums/discord servers/IRC channels instead.

That being said it seems like your wine prefix is 32 bit, you'll have to create a 64 bit one (weird considering that 64 bit should be the default). Basically follow https://wiki.winehq.org/FAQ#How_do_I_create_a_32_bit_wineprefix_on_a_64_bit_system.3F but replace 32 with 64.

**Comment by daedhel** [comment]
Sorry about that. Should I erase the report? Not sure if I can...
