### ISSUE TITLE
Windows EXE doesn't work under Wine (bug fixed in newer PyInstaller)

### ISSUE THREAD

**Issue by mrpippy** [derrod/legendary#341]
## Platform

Operating system and version: macOS 11.6, running CrossOver 21
Legendary version (`legendary -V`): 0.20.10

## Expected Behavior

Legendary should run

## Current Behavior

Legendary fails to run and prints an error from PyInstaller's bootloader:
```
$ wine ~/Downloads/legendary.exe 
[184] INTERNAL ERROR: cannot create temporary directory!
```

## Steps to Reproduce

1. Download the single EXE
2. Run with Wine on Linux or Mac
3.
4.

## Additional information

This is a [known issue](https://github.com/pyinstaller/pyinstaller/issues/4628), introduced in PyInstaller v3.6 and fixed in [PyInstaller v4.2](https://pyinstaller.readthedocs.io/en/v4.2/CHANGES.html).
Building the EXE with PyInstaller v4.2 or newer should fix the issue.

**Comment by derrod** [comment]
That is not a supported use-case.

**Comment by derrod** [comment]
@mrpippy FYI the latest releases should work now as I updated to PyInstaller 4.7.

But seeing as I now have a Mac and ship a native mac version and you added that PR to Heroic, I wondered if you could could maybe answer a few questions I have in relation to using CrossOver with legendary:

1. Can users install the Windows Epic Launcher via CrossOver? If there's a default localtion for that I'd like to add it to the locations searched (like with Lutris) for import/sync setup
2. Is it sensible to look for a CrossOver `wine` binary if the user does not have it installed otherwise, or does it require the supporting infrastructure of the app to setup a prefix etc.?
3. Can the setup detailed in the [Heroic guide on the website](https://www.codeweavers.com/support/wiki/mac/mactutorial/heroiclauncher) be automated, e.g. via command-line or does it have to be done through the GUI?

Unfortunately my trial has expired already so I cannot test all of those myself, but I'd be curious if utilising CrossOver is something worth looking into to make it easier to run Windows titles on macOS, especially when the first-party GUI is ready.

Thanks for your time (and work on CrossOver/WINE)!

**Comment by macosgupta** [comment]
@derrod 

1. You can install it, but it won't launch.  Older versions worked to some extent, but the current patch either crashes or doesn't render, only opens to a black screen.  

2. Crossover's mode of operation is to create prefixes called Bottles.  These are located by default at ~/Library/Application Support/Crossover/Bottles or ~/Documents/Bottles, but they can be relocated by the user.  The problem with using Crossover's wine is knowing which bottle to pass to the binary.  Heroic gets past this with its manual setup scheme.  

3) Crossover bottles are portable.  As long as you don't install any licensed software into it, there's no reason why you couldn't set it up once, export the bottle, and distribute the .cxbottle file, which is just a tar.gz of the prefix.  I can provide an example if you want to try to parse the configuration.

**Comment by derrod** [comment]
Thanks, I've not yet looked into distributing exported bottles, but it may be something worth doing for cases where it requires more than just the basic setup (which is fairly simple, I've already added a wiki article here: https://github.com/derrod/legendary/wiki/CrossOver-Setup-(macOS)). 

I've also had a friendly conversation with one of the CodeWeavers peeps and they were very helpful to answer some more questions regarding CrossOver.
