### ISSUE TITLE
Can't launch Batman Arkham Asylum (Linux)

### ISSUE THREAD

**Issue by dfireBird** [derrod/legendary#37]
I installed Batman™ Arkham Asylum Game of the Year Edition (App name: Godwit, version: 1.93). But when I try to launch it I got a error: 
`wine: cannot find '/home/firebird/legendary/BatmanArkhamAsylum/Binaries/Batman.exe'`
So I checked the files using `list-files` command it includes `Batman.exe` but it's not downloaded so I can't launch it.

**Comment by dfireBird** [comment]
I tried the command specified in issue #34 but that too didn't work sadly. I'm on Arch with legendary installed from AUR.

**Comment by derrod** [comment]
Did you interrupt and restart the download process at some point?

Try running `legendary list-files <app name> --hashlist > /home/firebird/legendary/BatmanArkhamAsylum/hashlist.sha1` and the within the installation directory run `sha1sum -c hashlist.sha1` to see which files are missing/corrupted. Probably a good idea to pipe it to a file since there are quite a lot of files in that game.

**Comment by dfireBird** [comment]
I have an unstable internet so the process is interrupted and restarted several times and also I ran the hash sum I have 9 files which are missing. These are the 9 files:
```
Binaries/APEX_debug.dll
Binaries/APEX_Destructible.dll
Binaries/APEX_Particles.dll
Binaries/APEX_release.dll
Binaries/APEX_RRB.dll
Binaries/Batman.exe
Binaries/binkw32.dll
Binaries/BmLauncher.exe
Binaries/BmLauncherUtils.dll
```

Note: All of these files are the first 9 files that comes after `list-files` command

**Comment by dfireBird** [comment]
I misread the `--prefix` documentation I thought you should mention files but instead it need path I tried the path `Binaries` and it worked. Thanks for creating this wonderful program.
