### ISSUE TITLE
Usernames with special characters are not handled properly

### ISSUE THREAD

**Issue by CommandMC** [derrod/legendary#398]
## Platform

Operating system and version: Arch Linux, kernel 5.16.2-arch1-1
Legendary version (`legendary -V`): 0.20.24

## Expected Behavior

Launching games while having a username with special characters should work fine

## Current Behavior

Legendary tries to insert the username (`-epicusername=XXX`) and launch the game. If the username has special characters, the launch will fail since subprocess tries to encode the parameters into ascii, which doesn't support most characters

## Steps to Reproduce

1. Have an account that has a special character in the name
2. Try to launch a game

## Additional information

Traceback of the issue (this is from Legendary v0.20.22 as that's bundled with Heroic):
```
Traceback (most recent call last):
  File "legendary/cli.py", line 2317, in <module>
  File "legendary/cli.py", line 2244, in main
  File "legendary/cli.py", line 646, in launch_game
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1754, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode character '\xf8' in position 18: ordinal not in range(128)
[7780] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by derrod** [comment]
Curious, what does `sys.getfilesystemencoding()` (in python) and `locale -a` (in the shell) say?

**Comment by CommandMC** [comment]
I myself can't reproduce this, we're on the Heroic Discord in \#linux there
Just thought I'd open an issue so it isn't forgotten about

**Comment by derrod** [comment]
Based on the conversation in that channel the user did not have their system configured correctly so UTF-8 wasn't working as expected. I *could* implement a workaround to encode parameters to ascii if the OS locale is `C` rather than any that supports unicode but that seems like a lot of work to fix something that the user should correct in their OS configuration.

They can of course still use the configuration option to override the username to work around this as well.
