### ISSUE TITLE
Review import function

### ISSUE THREAD

**Issue by guglicap** [derrod/legendary#45]
Hello, 

today I was trying to import GTAV from on older install I had, but it wouldn't let me because it would've had to download 240/340 files, clearly outside of the 95% match range.

Out of curiosity, I removed the check from `cli.py` and it imported the game, marking it as installed, so I could now run verify, and it turned out I only actually had to download 17GB instead of the whole 90GB.

I also tried to run `legendary repair` first, but it refused to do that because the game wasn't marked as installed. 

My suggestion would be to rewrite the import function to mark the game as installed (maybe after checking for conflicts, such as an already existing manifest but for another game, or same path as another installed game, etc) and run repair on it. This change wouldn't impact importing installations which are 100% perfect as repair would do nothing but it allows to import game installations which are in a broken state without having to download the whole game again. 

I'd like to hear your opinion on this as there might be something I'm missing here.

**Comment by derrod** [comment]
Well the import functionality was mostly meant to import already full installs that exist. The check is there to alert users if they might not have specified the correct path.

However I think a check for the game executable + a warning that the game might be incomplete rather than completely aborting would be sufficient. Users will have to run a repair anyway if they want the game to be updateable.

**Comment by guglicap** [comment]
Yeah I guess giving the user the choice to go through with the importing even if something looks off might be a good idea, although it's probably best to leave the default as it is. Maybe add an option, something like `--skip-missing-check`?

**Comment by derrod** [comment]
I changed the check and made it skippable.
