### ISSUE TITLE
[Feature request] Download Update Only

### ISSUE THREAD

**Issue by FloatingMind12** [derrod/legendary#458]
Is it possible to download only the update of a game?
I already have the game installed on one PC and I want to download its update from another completely different PC that doesn't have it installed without having to reinstall everything from scratch again. To put it bluntly: only download the newly added/modified files between two versions.

**Comment by derrod** [comment]
No.

**Comment by derrod** [comment]
To elaborate (because I was on my phone earlier): You can't really do that, you need the old manifest to even determine what the changed files are. And I really see no point in implementing this. For many games you'd probably have to download most of the game regardless due to them relying on large package files that contain all the assets.
