### ISSUE TITLE
Game not recognized as installed when installing with '--exclude' option

### ISSUE THREAD

**Issue by jllllll** [derrod/legendary#492]
## Platform
Operating system and version: Windows 10 21H2 (OS Build 19044.2130)
Legendary version (`legendary -V`): 0.20.30

## Expected Behavior
Game should install and be recognized as such like other games.

## Current Behavior
Game will 'install' just fine, however Legendary will not list it in installed games.

## Steps to Reproduce
Set of commands to reproduce using Fallout 3:

1. `legendary install adeae8bbfc94427db57c7dfecce3f1d4 --exclude "Fallout 3 GOTY French" --exclude "Fallout 3 GOTY German" --exclude "Fallout 3 GOTY Italian" --exclude "Fallout 3 GOTY Spanish"`
2. `legendary launch adeae8bbfc94427db57c7dfecce3f1d4`

## Additional information
You can work around this using:
`legendary import adeae8bbfc94427db57c7dfecce3f1d4 *path to game* --disable-check`

However, this is still an issue given that Fallout 3 is supposed to be ~8 GB, but since it uses a separate copy of the game for each supported language, the file size balloons to ~44 GB making it unnecessarily prohibitive in disk space. PCGamingWiki currently recommends EGS owners to use Legendary to get around this. Given that Fallout 3 is being given away for free on EGS, more people are bound to run into this issue.

**Comment by derrod** [comment]
This is expected, since Legendary has no way of keeping track what was excluded when updating, or exclusions could break an install with future updates. The game is DRM free anyway, so you can just run it directly. If you insits on running it through legendary you can try importing it after the download with the option to skip file verification.
