### ISSUE TITLE
Errors in python scripts when running most commands

### ISSUE THREAD

**Issue by theunofficialboss** [derrod/legendary#507]
## Platform

Operating system and version: Windows 10 21H2
Legendary version (`legendary -V`): 0.20.31 exe file

## Expected Behavior

run repair, listing, auth or installing commands

## Current Behavior

reporting errors in python scripts.
tried deleting .config files to reset legendary but programs continue to get installed with missing files
![image](https://user-images.githubusercontent.com/99676445/206877272-8acd5fe9-abe1-484f-a96b-9537d7ef5817.png)

## Steps to Reproduce

1. run legendary commands from cmd.exe in the legendary.exe directory

**Comment by CommandMC** [comment]
As you can see from the error message, Legendary is trying to export your installed game to the Epic Games Launcher (because you, in the past, enabled EGL Sync). However, the folder for it in `C:\ProgramData` is missing, likely because you've uninstalled the EGL.

Resolving this issue should be as easy as running `legendary egl-sync --disable-sync`

**Comment by theunofficialboss** [comment]
I removed EGL sync (my mistake sorry), but the game still installs with missing files
when running the game, an error pops up saying "The code execution cannot proceed because MSVCP100.dll was not found".
I tried using repair and downloading the individual dll file it self but I am returned with 0 files to download as the game was "already up to date". Is this a problem with Epic downloads or my drivers? I just downloaded the newest C++ distributable but I might have to reinstall Directx 12
