### ISSUE TITLE
Legendary may have problem parsing string encodes.

### ISSUE THREAD

**Issue by eebssk1** [derrod/legendary#550]
The error is throwed from Heroic Games Launcher.
Pls see this post https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/2590
Looks like some encoding issue?

**Comment by zclimber** [comment]
This issue is not limited to Chinese locale, it seems. I have a very similar one after upgrade, with Russian locale.

`
+ Sand Patch Grade (App name: 098b530746fa4cfb8b11484bfdc18a2d | Version: 1.0.2)[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Getting game list... (this may take a while)Traceback (most recent call last):
File "legendary\cli.py", line 3069, in <module>
File "legendary\cli.py", line 2980, in mainFile "legendary\cli.py", line 272, in list_games
File "encodings\cp1251.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\xf6' in position 24: character maps to <undefined>
[23984] Failed to execute script 'cli' due to unhandled exception!`

This might need a more thorough fix.

**Comment by zclimber** [comment]
> This issue is not limited to Chinese locale, it seems. I have a very similar one after upgrade, with Russian locale.
> 
> ```
> + Sand Patch Grade (App name: 098b530746fa4cfb8b11484bfdc18a2d | Version: 1.0.2)[cli] INFO: Logging in...[Core] INFO: Trying to re-use existing login session...[cli] INFO: Getting game list... (this may take a while)Traceback (most recent call last):
> File "legendary\cli.py", line 3069, in <module>
> File "legendary\cli.py", line 2980, in mainFile "legendary\cli.py", line 272, in list_games
> File "encodings\cp1251.py", line 19, in encode
> UnicodeEncodeError: 'charmap' codec can't encode character '\xf6' in position 24: character maps to <undefined>
> [23984] Failed to execute script 'cli' due to unhandled exception!
> ```
> 
> Also, changing encoding in Legendary is bad taste, what we should do is pass correct encoding from Heroic.

Except we can't pass correct encoding from Heroic, because PyInstaller ignores it. https://github.com/pyinstaller/pyinstaller/issues/2032

I propose Legendary unilaterally set encoding to utf-8 if stdout is not tty(interactive console).

**Comment by fingolfin** [comment]
Also had this using Heroic on a Steam Deck, where the offending character was `\xae`, i.e., `®` the registered trademark symbol.

**Comment by fingolfin** [comment]
It seems @derrod committed a fix for this in 8b2809779f94caee24b5ddc0464e744bf776527e -- thank you!

It would be great if there also was a release of Legendary with this fix in it, so that downstream distros can pick it up more easily :-).

**Comment by derrod** [comment]
I intended to add some other fixes for the next release, but just haven't gotten around to it. I might try to get one out on the weekend or something to also add a warning for games requiring the new Epic Online Services to be installed.

**Comment by derrod** [comment]
Will ship in an update soon™
