### ISSUE TITLE
EUFN Seems to Not be Properly Supported

### ISSUE THREAD

**Issue by Lone15** [derrod/legendary#576]
Platform: Windows 10 Enterprise LTSC
Legendary version: Latest
## Expected Behavior
Ideally EUFN should be launchable from the legendary base menu, as all sources report it is when using the epic games launcher.
## Current Behavior
When "legendary launch Fortnite_Studio" is entered, the text "[cli] ERROR: Fortnite_Studio is DLC; please launch the base game instead!" is returned.
## Steps to Reproduce
1. Add EUFN to account
2. Try to launch EUFN from legendary base menu
3. Unable to launch EUFN

## Additional information
It's notable that it doesn't seem to be possible to launch EUFN from inside of Fortnite (ala Save The World), otherwise I would have done so.

**Comment by derrod** [comment]
DLCs generally don't have executables, so at the time this made sense. Is there anything preventing you from just running the executable manually?

Anyway, this is a fairly straightforward change, since essentially all that needs to happen is have this line check if the DLC has an executable set:
https://github.com/derrod/legendary/blob/master/legendary/cli.py#L582-L584

**Comment by derrod** [comment]
Should be fixed with https://github.com/derrod/legendary/commit/07a16f7b84f4b6b43078fe84160ca761f1086ba4.

Not sure when a new version will ship though.
