### ISSUE TITLE
Clarify which platforms are available

### ISSUE THREAD

**Issue by marco97pa** [derrod/legendary#93]
I read the documentation and in many commands such as `install `or `list-games` there is the `--platform` filter.
There is no explanation on which platforms are available.
With some random tests I discovered that there are:

- Win32 (Windows 32 bit)
- Mac (Mac OS)

I still haven't found anything for x64 Windows games.
It would be useful to add this platforms on the help.
 I can add this information to the help of the app myself, if only knew all the platforms

**Comment by derrod** [comment]
I don't think the platforms are officially documented anywhere, the option was also only really added because some people wanted to be able to download certain platform specific builds for research purposes. Installing will be disabled if you specify a platform anyway.

The ones that seem to be valid are:
* `Windows`
* `Win32`
* `Mac`
* `Android`
* `IOS`

There may be more that just don't have any games available right now. I think even `Linux` is a valid platform in the backend, there's just nothing there.

In most cases only `Windows` exists, and `Win32` will likely be the same build if it does exist.

If you want you can add it to the wiki, but I don't see any reason to add this information to the software itself since it's only useful in rare circumstances.
