### ISSUE TITLE
Automatic installation not available on Linux

### ISSUE THREAD

**Issue by rdabra3** [derrod/legendary#96]
```
[DLManager] INFO: All done! Download manager quitting...
This game lists the following prerequisites to be installed:
- THCPrereqBundle: Binaries/Redist/BorderlandsInstaller.exe
[cli] INFO: Automatic installation not available on Linux.
[cli] INFO: This game supports cloud saves, syncing is handled by the "sync-saves" command.
[cli] INFO: To download saves for this game run "legendary sync-saves Dodo"
[cli] INFO: Finished installation process in 1903.29 seconds.
```
I am using Manjaro and I don't know how to install THCPrereqBundle dependency. Please help me!
![legendary_screenshot](https://user-images.githubusercontent.com/25562421/92814362-a5511600-f3e0-11ea-8561-87958053cc81.png)

**Comment by JoaoForce** [comment]
apparently it is a game dependency, legendary works correctly, I recommend looking for something related in the game forum, trying to create a wine prefix just for him is using winetricks by installing some dependencies on it

**Comment by derrod** [comment]
Those are just the game's dependencies, chances are that you don't even need to install them (I've run Borderlands before in Proton and didn't need to install them.). Legendary doesn't do it automatically on Linux because it has no idea what wine binary or prefix you'll be using to run the game. So if there's an issue with the game just run the listed .exe with the wine prefix and version you wanted to use for the game.
